version: '3.1' # Usa a versão 3.1 do Docker Compose

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: whitelabel
      POSTGRES_USER: whitelabel
      POSTGRES_PASSWORD: whitelabel
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
